index: # la route #
    path: / # le chemin #
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\LoginController::login     
    
register:
    path: /register
    controller: App\Controller\LoginController::register

postregister:
    path: /register
    controller: App\Controller\LoginController::postregister    
    methods: [POST] 